routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth/login');
});

Auth::routes();

Route::group(['middleware' => 'auth'], function() {

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::resource('sales-rep', App\Http\Controllers\SalesRepController::class);

});

app/Models/CurrentRoute.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class CurrentRoute extends Model
{
    use HasFactory;

    public $timestamps = false;

     /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'address'
    ];
}

app/Models/SalesRep.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class SalesRep extends Model
{
    use HasFactory, SoftDeletes;

     /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'joined_date',
        'current_route_id',
        'comment',
    ];

    

    public function currentRoute()
    {
        return $this->belongsTo(currentRoute::class);
    }
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/SalesRepController.php
<?php

namespace App\Http\Controllers;

use App\Repositories\Repository;
use App\Http\Requests\SalesRep\CreateRequest;
use App\Http\Requests\SalesRep\UpdateRequest;
use App\Models\CurrentRoute;
use App\Models\SalesRep;

class SalesRepController extends Controller
{
  
   protected $model;
   protected $currentRoute;

   public function __construct(SalesRep $salesRep, CurrentRoute $currentRoute)
   {
      // set the model
      $this->model = new Repository($salesRep);
      $this->currentRoute = new Repository($currentRoute);
   }


   /**
    * Display a listing of the resource.
    *
    * @return \Illuminate\Http\Response
    */

   public function index()
   {

      $salesReps = $this->model->getModel()->latest()->paginate(5);

      return view('sales-reps.index', compact('salesReps'))
         ->with('i', (request()->input('page', 1) - 1) * 5);
   }


   /**
    * Show the form for creating a new resource.
    *
    * @return \Illuminate\Http\Response
    */
   public function create()
   {

      $currentRoutes = $this->currentRoute->getModel()->pluck('address', 'id');

      return view('sales-reps.create', compact('currentRoutes'));
   }

   /**
    * Store a newly created resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @return \Illuminate\Http\Response
    */

   public function store(CreateRequest $request)
   {

      try {
         $this->model->create($request->all());

         return redirect()->route('sales-rep.index')->with('success', 'Record created successfully');
      } catch (\Exception $e) {

         return redirect()->back()->with('error', $e->getMessage());
      }
   }

   /**
    * Display the specified resource.
    *
    * @param  \App\Models\SalesRep  $salesRep
    * @return \Illuminate\Http\Response
    */

   public function show($id)
   {
      return $this->model->show($id);
   }


   /**
    * Show the form for editing the specified resource.
    *
    * @param  \App\Models\SalesRep  $salesRep
    * @return \Illuminate\Http\Response
    */
   public function edit($id)
   {


      if ($this->model->show($id)) {

         $model = $this->model->show($id);

         $currentRoutes = $this->currentRoute->getModel()->pluck('address', 'id');

         return view('sales-reps.edit', compact('currentRoutes', 'model'));
      }
   }

   /**
    * Update the specified resource in storage.
    *
    * @param  \Illuminate\Http\Request  $request
    * @param  \App\Models\SalesRep  $salesRep
    * @return \Illuminate\Http\Response
    */

   public function update(UpdateRequest $request, $id)
   {

      try {
         $this->model->update($request->all(), $id);

         return redirect()->route('sales-rep.index')->with('success', 'Record updated successfully');
      } catch (\Exception $e) {

         return redirect()->back()->with('error', $e->getMessage());
      }
   }

   /**
    * Remove the specified resource from storage.
    *
    * @param  \App\Models\SalesRep  $salesRep
    * @return \Illuminate\Http\Response
    */

   public function destroy($id)
   {

      try {
         $this->model->delete($id);

         return redirect()->route('sales-rep.index')->with('success', 'Record Deleted successfully');
      } catch (\Exception $e) {

         return redirect()->back()->with('error', $e->getMessage());
      }
   }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                        @if (Route::has('login'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                        @endif

                        @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                        @endif
                        @else

                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="{{ route('sales-rep.index') }}" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ __('Sales Representatives') }}
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('sales-rep.index') }}">
                                    {{ __('List Sales Representatives') }}
                                </a>
                            </div>
                        </li>

                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }}
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                    @csrf
                                </form>
                            </div>
                        </li>

                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @include('layouts.includes.flash-message')
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/includes/flash-message.blade.php
 <div class="container">
     <div class="row justify-content-center">
         <div class="col-md-12">
             @if ($message = Session::get('success'))
             <div class="alert alert-success">
                 <button type="button" class="close" data-dismiss="alert">×</button>
                 <p>{{ $message }}</p>
             </div>
             @endif

             @if ($message = Session::get('error'))
             <div class="alert alert-danger alert-block">
                 <button type="button" class="close" data-dismiss="alert">×</button>
                 <strong>{{ $message }}</strong>
             </div>
             @endif

             @if ($message = Session::get('warning'))
             <div class="alert alert-warning alert-block">
                 <button type="button" class="close" data-dismiss="alert">×</button>
                 <strong>{{ $message }}</strong>
             </div>
             @endif

             @if ($message = Session::get('info'))
             <div class="alert alert-info alert-block">
                 <button type="button" class="close" data-dismiss="alert">×</button>
                 <strong>{{ $message }}</strong>
             </div>
             @endif

             @if ($errors->any())
             <div class="alert alert-danger">
                 <button type="button" class="close" data-dismiss="alert">×</button>
                 Please check the form below for errors
             </div>
             @endif
         </div>
     </div>
 </div>

resources/views/sales-reps/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="row align-items-center my-4">
                <div class="col">
                    <h2 class="h3 mb-0 page-title">{{ __('Create Sales Representative') }}</h2>
                </div>
                <div class="col-auto">

                    <a href="{{route('sales-rep.index')}}" class="btn btn-primary" style="color:white">
                        <span style="color:white"></span> {{ __('Back to List') }}
                    </a>

                </div>
            </div>
            <div class="content-header row">
                <div class="content-header-left col-md-12 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="breadcrumb-wrapper col-12">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{route('home')}}">{{ __('Dashboard') }}</a></li>
                                <li class="breadcrumb-item"><a href="{{route('sales-rep.index')}}">{{ __('Sales Team') }}</a></li>
                                <li class="breadcrumb-item active">{{ __('Create Sales Representative') }}</li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>


            <div class="card shadow mb-4">
                <div class="card-body">
                    {!! Form::open(array('route' => 'sales-rep.store','method'=>'POST')) !!}
                    @include('sales-reps.includes.form')

                    {!! Form::close() !!}
                </div>
            </div> <!-- / .card -->
        </div> <!-- .col-12 -->
    </div> <!-- .row -->
</div> <!-- .container-fluid -->

@endsection

resources/views/sales-reps/delete.blade.php
<form action="{{ route('sales-rep.destroy', $salesRep->id) }}" method="post" enctype="multipart/form-data">
    {{ method_field('delete') }}
    {{ csrf_field() }}
    <div class="modal fade" id="ModalDelete{{$salesRep->id}}" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">{{ __('Delete') }}</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>   
                <div class="modal-body">You sure you want to delete <b>{{$salesRep->name}}</b>?</div>
                <div class="modal-footer">
                    <button type="button" class="btn gray btn-outline-secondary" data-dismiss="modal">{{ __('Cancel') }}</button>
                    <button type="submit" class="btn btn-outline-danger">{{ __('Delete') }}</button>
                </div>
            </div>
        </div>
    </div>   
</form>

resources/views/sales-reps/edit.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="row align-items-center my-4">
                <div class="col">
                    <h2 class="h3 mb-0 page-title">{{ __('Edit Sales Representative') }}</h2>
                </div>
                <div class="col-auto">

                    <a href="{{route('sales-rep.index')}}" class="btn btn-primary" style="color:white">
                        <span style="color:white"></span> {{ __('Back to List') }}
                    </a>

                </div>
            </div>
            <div class="content-header row">
                <div class="content-header-left col-md-12 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="breadcrumb-wrapper col-12">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{route('home')}}">{{ __('Dashboard') }}</a></li>
                                <li class="breadcrumb-item"><a href="{{route('sales-rep.index')}}">{{ __('Sales Team') }}</a></li>
                                <li class="breadcrumb-item active">{{ __('Edit Sales Representative') }}</li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
      
            <div class="card shadow mb-4">
                <div class="card-body">
                    {!! Form::model($model, ['method' => 'PATCH','route' => ['sales-rep.update', $model->id]]) !!}
                     @include('sales-reps.includes.form')

                    {!! Form::close() !!}
                    
                </div>
            </div> <!-- / .card -->
        </div> <!-- .col-12 -->
    </div> <!-- .row -->
</div> <!-- .container-fluid -->

@endsection

resources/views/sales-reps/includes/form.blade.php
<div class="row">

    @isset($model)

    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            {!! Form::label('ID:') !!}
            {!! Form::text('id', $model->id, array('disabled' => true,'class' => 'form-control')) !!}
        </div>
    </div>

    @endisset

    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            {!! Form::label('full_name:*') !!}
            {!! Form::text('name', null, array('placeholder' => 'Enter full name','class' => 'form-control')) !!}
            @error('name')
            <label class="text-danger">{{ $message }}</label>
            @enderror
        </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            {!! Form::label('email:*') !!}
            {!! Form::text('email', null, array('placeholder' => 'Enter email','class' => 'form-control')) !!}
            @error('email')
            <label class="text-danger">{{ $message }}</label>
            @enderror
        </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            {!! Form::label('telephone number:') !!}
            {!! Form::number('telephone', null, array('placeholder' => 'Enter telephone number','class' => 'form-control')) !!}
            @error('telephone')
            <label class="text-danger">{{ $message }}</label>
            @enderror
        </div>
    </div>


    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">

            {!! Form::label('joined_date:*') !!}
            {!! Form::date('joined_date', null, array('placeholder' => 'Select joined date','class' => 'form-control')) !!}
            @error('joined_date')
            <label class="text-danger">{{ $message }}</label>
            @enderror
        </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">

            {!! Form::label('current_route:') !!}
            {!! Form::select('current_route_id', $currentRoutes, null, ['class' => ['form-control'],'placeholder' => 'Select current route']) !!}
            @error('current_route_id')
            <label class="text-danger">{{ $message }}</label>
            @enderror
        </div>
    </div>

    <div class="col-xs-12 col-sm-12 col-md-12">
        <div class="form-group">
            {!! Form::label('comment:') !!}
            {!! Form::textarea('comment', null, [ 'placeholder' => 'Select comment', 'rows' => '3', 'class' => 'form-control']) !!}
            @error('comment')
            <label class="text-danger">{{ $message }}</label>
            @enderror
        </div>
    </div>

</div>

<div class="col-xs-12 col-sm-12 col-md-12 text-center">
    <button type="submit" class="btn btn-success"> {!! isset($model) ? __('Update') :__('Save') !!} </button>
</div>

resources/views/sales-reps/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="row align-items-center my-4">
                <div class="col">
                    <h2 class="h3 mb-0 page-title">{{ __('Sales Team') }}</h2>
                </div>
                <div class="col-auto">

                    <a href="{{ route('sales-rep.create') }}" class="btn btn-success" style="color:white">
                        <span style="color:white"></span> {{ __('Add New') }}
                    </a>

                </div>
            </div>
            <div class="content-header row">
                <div class="content-header-left col-md-12 col-12 mb-2">
                    <div class="row breadcrumbs-top">
                        <div class="breadcrumb-wrapper col-12">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="{{route('home')}}">{{ __('Dashboard') }}</a></li>
                                <li class="breadcrumb-item active">{{ __('Sales Team') }}</li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>


            <div class="row">
                <div class="col-md-12">
                    <div class="card shadow">
                        <div class="card-body">
                            <!-- table -->
                            <table class="table datatables" id="dataTable-1">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>{{ __('Name') }}</th>
                                        <th>{{ __('Email') }}</th>
                                        <th>{{ __('Telephone Number') }}</th>
                                        <th>{{ __('Current Route') }}</th>
                                        <th width="280px">{{ __('Action') }}</th>
                                    </tr>
                                </thead>
                                @foreach ($salesReps as $key => $salesRep)
                                <tbody>
                                    <tr>
                                        <td>{{ $salesRep->id }}</td>
                                        <td>{{ $salesRep->name }}</td>
                                        <td>{{ $salesRep->email }}</td>
                                        <td>{{ $salesRep->telephone }}</td>
                                        <td>{{ $salesRep->currentRoute->address ?? null }}</td>

                                        <td>
                                            <a class="btn btn-success" href="#" data-toggle="modal" data-target="#ModalShow{{$salesRep->id}}">{{ __('Show') }}</a>
                                            <a class="btn btn-primary" href="{{ route('sales-rep.edit',$salesRep->id) }}">{{ __('Edit') }}</a>
                                            <a class="btn btn-danger" href="#" data-toggle="modal" data-target="#ModalDelete{{$salesRep->id}}">{{ __('Delete')}}</a>
                                        </td>

                                        @include('sales-reps.show')
                                        @include('sales-reps.delete')

                                    </tr>
                                </tbody>
                                @endforeach
                            </table>

                            {!! $salesReps->render('pagination::bootstrap-4') !!}

                            {{-- {!! $salesReps->render() !!}  --}}
                            <!-- end table -->
                        </div>
                    </div>
                </div> <!-- .col-md-12 -->
            </div> <!-- end section row my-4 -->
        </div> <!-- .col-12 -->
    </div> <!-- .row -->
</div> <!-- .container-fluid -->


@endsection

resources/views/sales-reps/show.blade.php
    <div class="modal fade text-left" id="ModalShow{{$salesRep->id}}" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title"> {{ $salesRep->name }}</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>


                
                <div class="modal-body">

                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>{{ __('ID') }}:</strong>
                            {{ $salesRep->id }}
                        </div>
                    </div>

                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>{{ __('Full Name') }}:</strong>
                            {{ $salesRep->name }}
                        </div>
                    </div>

                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>{{ __('Email Address') }}:</strong>
                            {{ $salesRep->email }}
                        </div>
                    </div>

                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>{{ __('Telephone') }}:</strong>
                            {{ $salesRep->telephone }}
                        </div>
                    </div>

                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>{{ __('Joined Date') }}:</strong>
                            {{ $salesRep->joined_date }}
                        </div>
                    </div>

                     <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>{{ __('Current Route') }}:</strong>
                            {{ $salesRep->currentRoute->address ?? null }}
                        </div>
                    </div>

                    <div class="col-xs-12 col-sm-12 col-md-12">
                        <div class="form-group">
                            <strong>{{ __('Comment') }}:</strong>
                            {{ $salesRep->comment }}
                        </div>
                    </div>

        
                </div>
            </div>
        </div>
    </div>